// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

export interface LoginReq {
	phone: string
	password: string
}

export interface LoginResp {
	token: string
	expire: number
}

export interface LogoutReq {
}

export interface LogoutResp {
}

export interface RegisterReq {
	phone: string
	password: string
	nickname: string
	sex: number
	avatar: string
}

export interface RegisterResp {
	token: string
	expire: number
}

export interface User {
	id: string
	mobile: string
	nickname: string
	sex: number
	avatar: string
}

export interface UserInfoReq {
}

export interface UserInfoResp {
	info: User
}

